##### Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@2.1.0

# Replace this title as needed.
title: general.site_title
url: ""
baseurl: "/MI"
environment: staging
source: www

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  
#Map Layer
map_layers:
- min_zoom: 0
  max_zoom: 20
  staticBorders: false
  subfolder: laender
  label: indicator.map
  
map_options:
  disaggregation_controls: true
  minZoom: 5
  maxZoom: 10
#  limits: chroma.limits(data, 'e', 5)
  tileURL: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
  tileOptions:
    id: 'mapbox.light'
    accessToken: 'pk.eyJ1IjoiY2hyaXN0b3BoNDcxMSIsImEiOiJjanp1cjdpbzQwMTFwM29tdzJ2ZTh3Ymo4In0.C7_7e3AFcMaF_QBg6MaT0Q'
    attribution: '<a href="https://www.mapbox.com">Mapbox</a> | <a href="http://www.bkg.bund.de">© GeoBasis-DE / BKG | <a href="https://www.openstreetmap.org/copyright">&copy; OpenStreetMap</a>'
  colorRange: chroma.brewer.OrRd
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'  

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
  - Makefile
